### ISSUE TITLE
smtp_ip_address can't be hostname

### ISSUE THREAD

**Issue by Klaas-** [dell/omsdk#22]
# QwikContext
smtp_ip_address can't be a hostname, error message:
`IPAddressField returned failure for mail.example.com`
but using a hostname should be possible

# Details
According to https://raw.githubusercontent.com/dell/omsdk/devel/docs/OMSDK%20API%20Reference%20Guide.pdf it can be:
`"Enter the IPv4 or IPv6 address of the SMTP server or the FQDN / DNS name. The IP address  entered must be in the dot separated format. For example, 143.166.154.1."`
Using an IP works fine, using a fqdn/dns name does not work

# Repro Steps
I am not using the sdk directly, but via https://github.com/dell/dellemc-openmanage-ansible-modules
Reproduce via a simple task:
```
- name: Configure Mail Alerts
  dellemc.openmanage.dellemc_configure_idrac_eventing:
    idrac_ip: 123.123.123.123
    idrac_user: username
    idrac_password: password
    share_name: "{{ playbook_dir }}"
    email_alert_state: "Enabled"
    address: target@example.com
    smtp_ip_address: mail.example.com
    alert_number: 1
```

# Impact
Can not set a fqdn/dns name for smtp server, in our setup we have multiple smtp servers behind a round robin dns entry.

# NeedBy
Me and anyone not setting an IP as smtp server

Tested omsdk version: 1.2.478

# Severity
Severity 3
